### ISSUE TITLE
is there way to remove container content？

### ISSUE THREAD

**Issue by Richard-Choooou** [markdown-it/markdown-it-container#48]
same like.

before:
```javascript
::: example
there is a content
:::
```

after render:
```javascript
there is an other content
```

without the raw content

**Comment by Richard-Choooou** [comment]
I tryed to modify the token list
```javascript
render: (tokens, idx) => {
    if (tokens[idx].nesting === 1) {
        const config = tokens[idx + 2]
        for (let i = 0; i < 3; i++) {
            tokens.splice(idx + 3 - i, 1)
        }
        return `<div>
            <echarts-render echartsConfig="${config.content}"></echarts-render>
        `;
    } else {
        return '</div>';
    }
}
```

the well be throw error like this.
```log
./docs/line-charts.md
Module build failed (from ./node_modules/@vuepress/markdown-loader/index.js):
TypeError: Cannot read properties of undefined (reading 'type')
    at Renderer.render (C:\Users\zhoup\Desktop\project\front-end\cateyes-charts\node_modules\markdown-it\lib\renderer.js:321:22)
    at MarkdownIt.render (C:\Users\zhoup\Desktop\project\front-end\cateyes-charts\node_modules\markdown-it\lib\index.js:543:24)
    at MarkdownIt.md.render (C:\Users\zhoup\Desktop\project\front-end\cateyes-charts\node_modules\@vuepress\markdown\index.js:142:25)
    at Object.module.exports (C:\Users\zhoup\Desktop\project\front-end\cateyes-charts\node_modules\@vuepress\markdown-loader\index.js:74:16)
```

**Comment by CaiWenlie** [comment]
can use a html comment tag:
```
    if (tokens[idx].nesting === 1) {
        return `<div><!--`;
    } else {
        return '--></div>';
    }
```
